Ruby 3.1.2 update
wurmlab/sequenceserver pull request #590
Opened 2022-05-15 15:09 UTC by iQuxLE

With these updates SequenceServer is able to work on Ruby 3.1.2

2022-05-22 08:50 UTC, yeban requested changes
The first point about removing whitespace changes is essential. The second point probably requires some discussion.

2022-05-22 08:50 UTC, yeban commented on sequenceserver.gemspec
> +s.required_ruby_version = '>= 3.1.2'
I think we need to distinguish between ensuring seqserv works on latest Ruby and the minimum Ruby version we support. As a rule of thumb, the minimum Ruby version we want to support is the default Ruby of the oldest Ubuntu LTS that has not entered ESM phase yet. That would be Ubuntu 18.04 and the default for Ubuntu 18.04 is Ruby 2.5. So we should ideally have `>= 2.5.0` here.

2022-05-22 08:50 UTC, yeban commented on sequenceserver.gemspec
> +DESC
Please undo whitespace changes throughout this file. Currently it looks like the whole file has been rewritten.

2022-05-22 08:53 UTC, yeban commented on sequenceserver.gemspec
> +s.required_ruby_version = '>= 3.1.2'
Is it possible for us to support all the way from Ruby 2.5 to 3.1?

2022-05-22 09:34 UTC, yannickwurm commented
To keep things simple, I think we can decide that the next release is for 3.1. 

Yannick

2022-05-26 16:20 UTC, yeban commented on sequenceserver.gemspec
> +s.required_ruby_version = '>= 3.1.2'
I appreciate the reasoning that soon enough we will run into the next problem, but we should think from the user's point of view as well: Enforcing such a high minimum Ruby version constraint will make it harder for many existing users to upgrade and for new user to even try it out.

One way of approaching this is to test against multiple Ruby versions on Travis. Maybe just Ruby 2.5 and 3.1. That is, the minimum required and the latest. If installation and tests start failing for the minimum Ruby version and without a simple fix, we increase the minimum Ruby. It used to be the case earlier that we used to test against multiple Ruby versions. But there was a phase when our testing system went through a lot of changes. And it got too complex to test multiple Ruby versions while also experimenting with different approaches, so the number of Ruby versions to run the tests on was reduced. I think the test suite is in a much better position today (except 1-2 remaining random errors which I am sure we will get to as well).

2022-06-07 14:41 UTC, iQuxLE commented
The recent updates will make the sequenceserver usable for everyone from 2.5 to 3.1.2.

2022-07-31 21:24 UTC, yannickwurm commented
How can we get travis to run on this file?

2022-07-31 21:25 UTC, yannickwurm commented
(or perhaps we should just migrate to Github's built-in test runner - given that travis is also funny with timeouts)

2022-07-31 21:26 UTC, yannickwurm commented
@iQuxLE  - it looks like you haven't yet addressed some of the issues that have been raised

2022-08-01 08:25 UTC, iQuxLE commented
Gonna take care of this the next days.

2023-04-24 10:33 UTC, yannickwurm commented
Superseded by #637

2023-04-24 10:33 UTC, closed without merging